In [1]:
#1. Write a NumPy program to create an array with the values 1, 7, 13, 105    and determine the size of the memory occupied by the array.

In [14]:
import numpy as np

In [15]:
def arr():
    a1 = np.array([1,7,13,105])
    print(a1)
    print(a1.itemsize)
    print(a1.nbytes)

In [16]:
arr()

[  1   7  13 105]
8
32


In [17]:
# 2. Write a NumPy program to create an element-wise comparison (greater,    greater_equal, less and less_equal) of two given arrays.

In [18]:
def com(a):
    n1 = np.array([1,2,3,4,5,6,0])
    n2 = np.array([7,6,5,4,3,2,0])

    if n1[a] == n2[a] :
            print(f"both are same")
    elif n1[a] <= n2[a] :
            print(f" n2 is big")

    elif n1[a] >= n2[a] :
            print(f"n1 is  big")

In [19]:
com(5)

n1 is  big


In [20]:
# 3.  Write a NumPy program to create an array of 10 zeros, 10 ones, 10    fives, 10 tens, 10 twentys and 10 fiftys.
def a():
    q1 = np.zeros(10, dtype=np.int8)
    print(q1)
    q1 = np.ones(10, dtype=np.int8)
    print(q1)
    q1 = np.ones(10, dtype=np.int8)
    print(q1*5)
    q1 = np.ones(10, dtype=np.int8)
    print(q1*10)    
    q1 = np.ones(10, dtype=np.int8)
    print(q1*20)
    q1 = np.ones(10, dtype=np.int8)
    print(q1*50)

In [22]:
a()

[0 0 0 0 0 0 0 0 0 0]
[1 1 1 1 1 1 1 1 1 1]
[5 5 5 5 5 5 5 5 5 5]
[10 10 10 10 10 10 10 10 10 10]
[20 20 20 20 20 20 20 20 20 20]
[50 50 50 50 50 50 50 50 50 50]


In [23]:
# 4. Write a NumPy program to create an array of integers from 30 to 70.
# 5. Write a NumPy program to create an array of integers from 50 to 95.

In [27]:
def fun1():
    a1 = np.arange(30, 71)
    print(a1)
    a1 = np.arange(50, 96)
    print(a1)

In [28]:
fun1()

[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]
[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95]


In [29]:
# 6. Write a NumPy program to create an array of all even integers from 20 to 80.
def fun2():
    a1 = np.arange(20, 81, 2)
    print(a1)

In [30]:
fun2()

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66
 68 70 72 74 76 78 80]


In [31]:
# 7. Write a NumPy program to create an array of all odd integers from 20 to 80.

In [38]:
def fun3():
    a1 = np.arange(21, 81, 2)
    print(a1)

In [39]:
fun3()

[21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57 59 61 63 65 67
 69 71 73 75 77 79]


In [40]:
# 8. Write a NumPy program to generate an array of 15 random numbers from 10    to 40.

In [42]:
a2 = np.random.randint(10, 40,15)
print(a2)

[12 23 18 35 34 39 34 21 34 25 35 11 39 16 15]


In [43]:
# 9. Write a NumPy program to generate an array of 10 random numbers from 30    to 50.
a2 = np.random.randint(30, 50,10)
print(a2)


[31 44 35 39 30 38 32 42 31 33]


In [44]:
# 10. Write a NumPy program to generate an array of 20 random numbers from 50    to 90.
a2 = np.random.randint(50, 90,20)
print(a2)

[76 52 67 50 79 57 58 79 71 80 85 51 81 53 50 74 54 89 56 59]


In [47]:
# 11. Create any two arrays & perform various mathematical operations. i.e. Addition, Substraction, Multiplication, Divide.
a1 = np.array([1,2,3,4,5,6,1])
a2 = np.array([7,6,5,4,3,2,1])
print(a1 + a2) 
print(a1 - a2) 
print(a1 * a2) 
print(a1 / a2) 




[8 8 8 8 8 8 2]
[-6 -4 -2  0  2  4  0]
[ 7 12 15 16 15 12  1]
[0.14285714 0.33333333 0.6        1.         1.66666667 3.
 1.        ]


In [68]:
# 12. Write a NumPy program to create a 3x4 matrix filled with values from 10     to 21.

m = np.arange(10, 22).reshape((3, 4))

print(m)




[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [69]:
# 13. Write a NumPy program to create a 3x3 identity matrix, i.e. the diagonal     elements are 1, the rest are 0.

x = np.eye(3)
print(x)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [71]:
# 14. Write a NumPy program to find the number of rows and columns in a given     matrix. 

m = np.arange(10, 22).reshape((3, 4))

print(m)

print(m.shape)



[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
(3, 4)


In [73]:
# 15. Write a NumPy program to create a 5x5 zero matrix with elements on the     main diagonal equal to 1, 2, 3, 4, 5.




x = np.diag([1, 2, 3, 4, 5])

print(x)




[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [76]:
# 16. Write a NumPy program to create a 3x3x3 array filled with arbitrary values.


x = np.random.random((3, 3, 3))
print(x)


[[[0.36899626 0.10936734 0.18236859]
  [0.20421038 0.85266961 0.44978525]
  [0.81727902 0.21959924 0.92665384]]

 [[0.49015374 0.35568977 0.85416991]
  [0.15466955 0.95280469 0.97387686]
  [0.27427808 0.57403167 0.16820669]]

 [[0.60710132 0.3721937  0.88932697]
  [0.13915184 0.58542614 0.32248631]
  [0.55462647 0.57447224 0.84392422]]]


In [79]:
# 17. Write a NumPy program to create a 2x3x4 array filled with arbitrary     values.

x = np.random.random((2, 3, 4))
print(x)

[[[0.92160051 0.33192216 0.36297072 0.84157071]
  [0.68856016 0.63349464 0.92924459 0.41963949]
  [0.19414835 0.6616296  0.61596784 0.83099141]]

 [[0.91232096 0.3219249  0.68194356 0.49301884]
  [0.60575484 0.48421761 0.90611794 0.18586695]
  [0.4304405  0.68069537 0.00706725 0.40680719]]]


In [89]:
# 18. Write a NumPy program to convert a list of numeric values into a one-    dimensional NumPy array.

a = [1,2,3,4,5,6,7,8,9,0]
print(a)

c = np.array(a)
print(c)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
[1 2 3 4 5 6 7 8 9 0]


In [90]:
# 19. Write a NumPy program to create a 3x3 matrix with values ranging from 2     to 10.

a = np.arange(2, 11).reshape(3, 3)

print(a)



[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [91]:
# 20. Write a NumPy program to create an array with values ranging from 12 to 38.

a1 = np.arange(12, 39)
print(a1)



[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


In [93]:
# 21. Write a NumPy program to reverse an array (the first element becomes the last).

a1 = np.arange(12, 39)
print(a1)
a2 = a1[::-1]

print(a2)


[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]
[38 37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15
 14 13 12]


In [96]:
# 22. Write a NumPy program to convert an data type into to a floating type.

a = np.arange(12, 39)


x = np.asfarray(a)

print(x)

[12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29.
 30. 31. 32. 33. 34. 35. 36. 37. 38.]


In [97]:
# 23. Write a NumPy program to convert a list array.

a = [1,2,3,4,5,6,7,8,9,0]
print(a)

c = np.array(a)
print(c)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]
[1 2 3 4 5 6 7 8 9 0]


In [99]:
# 24. Write a NumPy program to get the element-wise remainder of an array of division.

a = np.arange(1, 10)
print(np.remainder(a, 5)) 

[1 2 3 4 0 1 2 3 4]


In [100]:
# 25. Write a NumPy program to get the element-wise remainder of an array of numbers from 20 to 50 which are divisible by 3.


a = np.arange(20, 50)
print(np.remainder(a, 3)) 

[2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1]
